INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'ES120', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'HQ164', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'HQ166', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'HQ167', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'HQ168', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'HQ169', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'HQ180', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'PL164', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'PL165', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'PL166', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'PL167', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'PL168', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'PL169', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'PL180', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'ES160', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'ES161', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'ES162', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'ES163', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'ES164', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'ES165', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'ES166', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'ES167', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'ES168', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'ES169', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'ES170', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'ES180', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'FR160', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'FR161', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'FR162', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'FR163', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'FR164', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'FR165', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'FR166', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'FR167', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'FR168', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'FR169', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'FR170', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'FR180', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'AU130', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'SH160', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'SH161', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'SH162', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'SH163', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'SH164', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'SH165', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'SH166', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'SH167', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'SH168', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'SH169', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'SH170', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'SH180', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'BR164', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'BR165', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'BR166', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'BR167', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'BR168', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'BR169', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'BR170', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'BR180', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'CA161', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'CA162', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'CA163', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'CA164', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'CA165', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'CA166', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'CA167', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'CA168', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'CA169', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'CA180', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK090', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK091', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK130', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK160', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK161', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK162', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK163', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK164', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK165', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK166', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK167', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK168', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK169', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK170', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK180', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'UK070', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'US162', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'US163', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'US164', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'US165', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'US166', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'US167', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'US168', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'US169', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'US180', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'US098', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'US099', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'Functions', 'Sales - Non-Acute', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'Functions', 'Sales - Operations', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'Functions', 'Sales - Acute', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'Functions', 'BU01 Injection and Pharma delivery', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'Functions', 'BU02 Diagnostics', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'Functions', 'BU03 Diabetes Care', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'Functions', 'BU04 Vascular Access & Infusion Therapy', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'Functions', 'BU05 Oncology', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'Functions', 'BU06 Infection Prevention', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'Functions', 'BU07 Kitting', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'Functions', 'BU08 Advanced Wound Care', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'Functions', 'BU09 Medical Supplies', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'Functions', 'BU10 Sol Cotton', 1);
INSERT INTO requestdata ([key], [value], [version]) VALUES ( 'Functions', 'BU11 Localization', 1);

Insert into requestdata ([key], [value], [version]) VALUES ( 'CostCenters', 'ES120', 1)


